// Frågebank för kompetenskörkortet. Map: leafId → lista av frågor.
// Varje fråga: { level (1-3), prompt, options (4 st), answer (index 0-3),
// explanation }. data.js förblir orörd; detta är en separat innehållsfil.
// Pilot: undergruppen "Kännedom om lagkrav" i rollen Fastighetsutvecklare.
window.QUIZ_DATA = {

  pbl: [
    { level: 1,
      prompt: "Vad styr i första hand vad som får byggas på en viss plats?",
      options: ["Detaljplanen", "Bygglovet", "Startbeskedet", "Bygganmälan"],
      answer: 0,
      explanation: "Detaljplanen reglerar markanvändningen; bygglovet prövas mot planen." },
    { level: 1,
      prompt: "Vad krävs normalt innan en bygglovspliktig åtgärd får påbörjas?",
      options: ["Slutbesked", "Startbesked", "Energideklaration", "Lagfart"],
      answer: 1,
      explanation: "Startbeskedet ger klartecken att börja bygga; slutbesked kommer först när allt är klart." },
    { level: 2,
      prompt: "En önskad åtgärd är planstridig. Vad är den normala vägen framåt?",
      options: ["Den får alltid beviljas ändå", "Den avgörs av entreprenören",
                "Den kräver planändring eller prövning av avvikelse", "Den är alltid förbjuden"],
      answer: 2,
      explanation: "Är åtgärden planstridig krävs planändring, eller prövning av om det är en tillåten avvikelse." },
    { level: 2,
      prompt: "Vad bör du säkerställa när du tidsätter ett projekt med bygglov?",
      options: ["Att lovet hanteras efter byggstart", "Att lov inte påverkar tidplanen",
                "Att entreprenören söker lovet", "Att lovskedet läggs in realistiskt i tidplanen"],
      answer: 3,
      explanation: "Lov- och anmälningsskeden tar tid och måste in i projektets tidplan från början." },
    { level: 3,
      prompt: "När bör planrelaterade risker helst identifieras?",
      options: ["I tidiga skeden, innan de blir dyra förseningar", "Vid slutbesiktning",
                "Efter byggstart", "När bygglovet avslås"],
      answer: 0,
      explanation: "Tidig identifiering gör att planrisker kan hanteras innan de blir kostsamma förseningar." },
    { level: 3,
      prompt: "Vad är ett planbesked?",
      options: ["Ett beslut om bygglov", "Kommunens besked om man är beredd att pröva en detaljplan",
                "Ett startbesked för bygge", "Ett miljötillstånd"],
      answer: 1,
      explanation: "Ett planbesked är kommunens besked om den är beredd att inleda en planläggning." }
  ],

  jordabalken: [
    { level: 1,
      prompt: "Vilken rättighet kan belasta en fastighet och ge någon annan rätt att använda en del av den?",
      options: ["Bygglov", "Bolagsordning", "Detaljplan", "Servitut"],
      answer: 3,
      explanation: "Ett servitut ger en fastighet rätt att använda en del av en annan fastighet." },
    { level: 1,
      prompt: "Var regleras köp av fast egendom?",
      options: ["Jordabalken", "Köplagen", "Avtalslagen", "Plan- och bygglagen"],
      answer: 0,
      explanation: "Köp av fast egendom (fastighet) regleras i jordabalken." },
    { level: 2,
      prompt: "Var hittar du tillförlitligt vilka rättigheter som belastar en fastighet?",
      options: ["I bygglovet", "I detaljplanen", "I fastighetsregistret", "Hos entreprenören"],
      answer: 2,
      explanation: "Fastighetsregistret visar belastande och förmånliga rättigheter på en fastighet." },
    { level: 2,
      prompt: "Vilken aktör beställer du åtgärder från för att bilda eller ändra servitut och fastighetsgränser?",
      options: ["Boverket", "Lantmäteriet", "Skatteverket", "Länsstyrelsen"],
      answer: 1,
      explanation: "Lantmäteriet hanterar fastighetsbildning, servitut och gränser." },
    { level: 3,
      prompt: "Vad kännetecknar ett väl utformat servitutsupplägg?",
      options: ["Att det gäller bara ett år", "Att det bara gynnar säljaren",
                "Att det inte behöver registreras", "Att det håller över tid trots ändrat ägande"],
      answer: 3,
      explanation: "Ett hållbart upplägg fungerar även när ägande och verksamhet förändras över tid." },
    { level: 3,
      prompt: "Hur förebygger man bäst framtida gräns- och rättighetstvister?",
      options: ["Genom tydliga avtal och servitut från början", "Genom att avvakta tills tvist uppstår",
                "Genom muntliga överenskommelser", "Genom att överlåta frågan till entreprenören"],
      answer: 0,
      explanation: "Tvister förebyggs genom hur avtal och servitut skrivs redan från början." }
  ],

  bfs2024: [
    { level: 1,
      prompt: "Vad reglerar Boverkets byggregler bland annat?",
      options: ["Brand, energi och tillgänglighet m.m.", "Endast fasadfärg",
                "Markpriser", "Upphandlingsförfaranden"],
      answer: 0,
      explanation: "BBR/BFS reglerar bl.a. utformning, brand, energi och tillgänglighet." },
    { level: 1,
      prompt: "Skiljer sig kraven i byggreglerna mellan olika typer av verksamheter?",
      options: ["Nej, samma krav alltid", "Bara för bostäder",
                "Bara för industri", "Ja, de skiljer mellan verksamhetsklasser"],
      answer: 3,
      explanation: "Kraven skiljer sig mellan olika verksamhetsklasser." },
    { level: 2,
      prompt: "Vad bör du som beställare göra med projekteringshandlingar i förhållande till BBR?",
      options: ["Lita helt på entreprenören", "Ignorera dem",
                "Granska att de uppfyller BBR-kraven", "Vänta till slutbesiktning"],
      answer: 2,
      explanation: "Du granskar att handlingarna följer brand-, energi- och tillgänglighetskrav." },
    { level: 2,
      prompt: "När bör en sakkunnig (t.ex. brand eller tillgänglighet) kopplas in?",
      options: ["Aldrig", "När projektet kräver särskild brand- eller tillgänglighetsbedömning",
                "Endast efter slutbesked", "Bara om kommunen kräver det skriftligt"],
      answer: 1,
      explanation: "Sakkunnig kopplas in när projektet kräver särskild bedömning av sådana krav." },
    { level: 3,
      prompt: "Hur hanteras ett motiverat avsteg från en byggregel på ett hållbart sätt?",
      options: ["Det görs muntligt", "Det undviks att nämnas",
                "Det beslutas av entreprenören ensam", "Det motiveras och dokumenteras"],
      answer: 3,
      explanation: "Avsteg ska motiveras och dokumenteras på ett hållbart sätt." },
    { level: 3,
      prompt: "Vad innebär det att vara intern referens i regeltolkning?",
      options: ["Att kollegor rådfrågar dig i svåra tolkningar", "Att du skriver reglerna",
                "Att du beslutar bygglov", "Att du ersätter Boverket"],
      answer: 0,
      explanation: "Du är den kollegorna vänder sig till i svåra regeltolkningar." }
  ],

  lou: [
    { level: 1,
      prompt: "Vad gäller för kommunala inköp enligt LOU?",
      options: ["De är alltid fria", "De beslutas av entreprenören",
                "De omfattas av upphandlingsplikt", "De kräver aldrig konkurrens"],
      answer: 2,
      explanation: "Offentliga inköp omfattas av upphandlingsplikt enligt LOU." },
    { level: 1,
      prompt: "Vad är en direktupphandlingsgräns?",
      options: ["Ett beloppstak under vilket direktupphandling får ske", "En gräns för byggnadshöjd",
                "En tidsgräns för bygglov", "En miljögräns"],
      answer: 0,
      explanation: "Under direktupphandlingsgränsen får inköp ske utan formellt förfarande." },
    { level: 2,
      prompt: "Vad avgör i första hand vilket upphandlingsförfarande som ska väljas?",
      options: ["Entreprenörens önskemål", "Väderleken",
                "Slumpen", "Värdet och behovet"],
      answer: 3,
      explanation: "Förfarandet väljs utifrån upphandlingens värde och behov." },
    { level: 2,
      prompt: "Vad bör du planera in i projektets tidplan kopplat till upphandling?",
      options: ["Inget, upphandling tar ingen tid", "Upphandlingens ledtider",
                "Endast byggtiden", "Endast garantitiden"],
      answer: 1,
      explanation: "Upphandlingens ledtider måste planeras in i projektets tidplan." },
    { level: 3,
      prompt: "Vad minimerar risken för överprövning i en upphandling?",
      options: ["Ett genomarbetat förfrågningsunderlag", "Att hoppa över annonsering",
                "Att förkorta anbudstiden maximalt", "Att välja billigaste utan kriterier"],
      answer: 0,
      explanation: "Ett tydligt, genomarbetat förfrågningsunderlag minskar risken för överprövning." },
    { level: 3,
      prompt: "Vad balanseras i en upphandlingsstrategi för stora, komplexa projekt?",
      options: ["Endast pris", "Endast leveranstid",
                "Endast entreprenörens vinst", "Pris, kvalitet och risk"],
      answer: 3,
      explanation: "Strategin väger pris, kvalitet och risk för överprövning mot varandra." }
  ],

  miljobalken: [
    { level: 1,
      prompt: "Vad kan finnas i marken på en plats och påverka ett projekts tid och kostnad?",
      options: ["Detaljplaner", "Bygglov", "Markföroreningar", "Servitut"],
      answer: 2,
      explanation: "Markföroreningar kan kräva sanering och påverkar tid och kostnad." },
    { level: 1,
      prompt: "Vad kan vissa åtgärder kräva enligt miljöbalken?",
      options: ["Bara bygglov", "Inget alls",
                "Endast startbesked", "Anmälan eller tillstånd"],
      answer: 3,
      explanation: "Miljöfarlig verksamhet och vissa åtgärder är anmälnings- eller tillståndspliktiga." },
    { level: 2,
      prompt: "Vad beställer du för att ta reda på om mark är förorenad?",
      options: ["En miljöteknisk markundersökning", "En detaljplan",
                "Ett bygglov", "En energideklaration"],
      answer: 0,
      explanation: "En miljöteknisk markundersökning visar om och hur marken är förorenad." },
    { level: 2,
      prompt: "Var bör saneringsåtgärder hanteras i projektet?",
      options: ["Utanför projektet", "I tidplan och budget",
                "Först efter inflyttning", "Av entreprenören utan beställarens vetskap"],
      answer: 1,
      explanation: "Sanering och miljöåtgärder läggs in i projektets tidplan och budget." },
    { level: 3,
      prompt: "Vad gör man med miljörisk i ett beslutsunderlag på expertnivå?",
      options: ["Ignorerar den", "Överlåter allt till konsult",
                "Värderar miljörisk mot affärsnytta", "Skjuter upp den till efter bygget"],
      answer: 2,
      explanation: "Man väger miljörisk mot affärsnytta i beslutsunderlaget." },
    { level: 3,
      prompt: "Varför vill man fånga miljörisker tidigt?",
      options: ["För att slippa bygglov", "För att höja priset",
                "Det spelar ingen roll när", "För att de inte ska spräcka projektet senare"],
      answer: 3,
      explanation: "Tidigt fångade miljörisker undviker dyra överraskningar som spräcker projektet." }
  ]

};
